(function(){/*

 Copyright (C) 2014-2015 tgckpg.

 @license
 Licensed under GPL licenses.
*/
function k(b,e){b.prototype=Object.create(e.prototype);b.prototype.constructor=b}function l(b,e,d){Object.defineProperty(b,e,{get:d,set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:e})})}function p(b,e){Object.defineProperty(b,"propagating",{get:e,set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:"propagating"})})}
function q(b,e,d){Object.defineProperty(b,e,{get:function(){return d},set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:e})})}function BotanEvent(b,e){var d=!1,c=!1;q(this,"propagate",function(){c||(d=!0);c=!0});q(this,"stopPropagating",function(){d=!1});q(this,"type",b);p(this,function(){return d});q(this,"data",e);this.setTarget=function(a){q(this,"target",a);this.setTarget=void 0}.bind(this)}
function t(){function b(){this.j.propagate();for(var a in this.stack)if(this.j.propagating)this.stack[a](this.j);this.j.stopPropagating()}function e(a){d[a]||(d[a]=[]);return d[a]}var d={},c=this;this.addEventListener=function(a,f){var c=e(a);c[c.length]=f};this.removeEventListener=function(a,f){var c=e(a),b=c.indexOf(f);0>b||delete c[b]};this.dispatchEvent=function(a){var f=e(a.type);a.setTarget&&a.setTarget(c);setTimeout(b.bind({j:a,stack:f}),0)}}function v(){t.call(this)}v.prototype=[];
var w={},x={},y={},A=window.BotanJS,BotanJS=null,B=null,C=null;A&&(BotanJS=A.sg[0],B=A.sg[1],C=A.sg[2]);BotanJS=BotanJS||function(){var b=0,e=[],d=[],c=new t,a={write:function(a){e[e.length]=a}};q(a,"read",function(){return e[b++]});q(a,"end",function(){return e.length<=b});q(c,"log",a);q(c,"define",function(a){d[d.length]=a});q(c,"getDef",function(){return d.slice()});return c}();
B=B||function(b){if(x[b])return x[b];for(var e=b.split("."),d=e.length,c=w,a=0;a<d;a++)c[e[a]]=c[e[a]]||{},c=c[e[a]];c.r=[];nsObj=new v;nsObj[1]=function(a,c,b){this.c[c]||(this.c[c]=[a,b],a=new BotanEvent("NS_EXPORT",{name:this.f+"."+c,type:a}),BotanJS.dispatchEvent(a))}.bind({c:c,f:b});nsObj[0]=function(a){if(!this.c[a])throw Error("["+this.f+"] Invoke failed: "+a+" does not exists");return this.c[a][1]}.bind({c:c,f:b});nsObj[10]=function(a,c){this.r[a]=c}.bind(c);nsObj[11]=function(a,c){throw Error("["+
this.f+(c?"."+c:"")+"] "+a);}.bind({f:b});BotanJS.dispatchEvent(new BotanEvent("NS_INIT",b));return x[b]=nsObj};
C=C||function(b,e){var d=b.replace(".*","");x[d]&&x[d].dispatchEvent(new BotanEvent("NS_IMPORT",f));if(!e&&y[b])return y[b];for(var c=b.split("."),a=c.length,f=w,d=!1,h=0;h<a;h++){if("*"==c[h]){d=!0;break}f=f[c[h]];if(!f)throw Error("No such class: "+b);}if(f instanceof Array&&"*"!=c[h])return d=null,d=10==f[0]?f[1]():f[1],y[b]=d;c={};for(h in f)a=f[h],a instanceof Array&&(d&&2==a[0]?c[h]=a[1]:3==a[0]?c[h]=a[1]:0==a[0]?Object.defineProperty(c,h,{get:function(){return this.c[this.a][1]}.bind({a:h,
c:f}),set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:h})}):1==a[0]?Object.defineProperty(c,h,{get:function(){return this.c[this.a][1]()}.bind({a:h,c:f}),set:function(a){this.c[this.a][1](a)}.bind({a:h,c:f})}):10==a[0]&&Object.defineProperty(c,h,{get:a[1],set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:h})}));return y[b]=c};window.BotanJS={};window.BotanJS.version="0.2";window.BotanJS.codename="Botanical framework.js";
window.BotanJS["import"]=function(b){try{return C(b)}catch(e){if(A)return A["import"](b);throw e;}};window.BotanJS.sg=[BotanJS,B,C];BotanJS.define("System.utils.IKey");
(function(){function b(d,c){d&&"string"!=typeof d||(this.keyName=d,this.keyValue=c instanceof b?c:void 0!=c?String(c):"",this.keyName=this.keyName,this.keyValue=this.keyValue)}var e=B("System.utils");b.prototype.keyName="";b.prototype.keyValue="";q(b,"quickDef",function(){var d=arguments.length;if(0!=d%2)e[11]("Invalid Definition Count","IKey");for(var c=[],a=0;a<d;a+=2)c[c.length]=new b(arguments[a],arguments[a+1]);return c});e[1](2,"IKey",b)})();BotanJS.define("System.utils.Perf");
(function(){for(var b=B("System.utils.Perf"),e=[],d=0;256>d;d++)e[d]=(16>d?"0":"")+d.toString(16);b[1](10,"uuid",function(){var c=4294967295*Math.random()|0,a=4294967295*Math.random()|0,f=4294967295*Math.random()|0,b=4294967295*Math.random()|0;return e[c&255]+e[c>>8&255]+e[c>>16&255]+e[c>>24&255]+"-"+e[a&255]+e[a>>8&255]+"-"+e[a>>16&15|64]+e[a>>24&255]+"-"+e[f&63|128]+e[f>>8&255]+"-"+e[f>>16&255]+e[f>>24&255]+e[b&255]+e[b>>8&255]+e[b>>16&255]+e[b>>24&255]});b[1](3,"ArrayReverse",function(c){for(var a=
null,f=c.length,b=null,a=0,b=f-1;a<b;a+=1,--b){var f=c[a],d=c[b],f=f^d,d=d^f,f=f^d;c[a]=f;c[b]=d}})})();BotanJS.define("System.Global");(function(){var b=B("System.Global"),e=Boolean(document.all),d=window.allowed_origins||[],c=window.location.href.match(/^https:\/\//);b[1](10,"debug",function(){return window.debugEnv&&window.debugEnv});b[1](0,"IE",e);b[1](0,"ALLOWED_ORIGINS",d);b[1](0,"SECURE_HTTP",c)})();BotanJS.define("Dandelion");
(function(){function b(){if(s)return!0;try{return s=C("Dandelion.IDOMElement"),!0}catch(a){}return!1}function e(a,c){if(c&&b()){for(var f=a.length,d=[],e=0;e<f;e++)d[e]=s(a[e]);return d}return a}function d(a,c){a&&c(a)&&a.parentNode&&d(a.parentNode,c)}function c(a,b){return b(a)?a:a.parentNode&&c(a.parentNode,b)}function a(a){return document.createTextNode(a)}function f(a,c,b,f,d){a=document.createElement(a||"div");c&&(a.id=c);b&&(n?a.className=b:a.setAttribute("class",b));if(d)if(d instanceof Array)for(var e in d)a.setAttribute(d[e].keyName,
d[e].keyValue);else d instanceof m&&a.setAttribute(d.keyName,d.keyValue);f&&h(a,f);return a}function h(c,b){if(b instanceof Array)for(var f=b.length,d=0;d<f;d++)b[d]&&h(c,b[d]);else"string"==typeof b?c.appendChild(a(b)):b&&c.appendChild(b)}var g=B("Dandelion"),n=C("System.Global.IE"),m=C("System.utils.IKey"),s;g[1](3,"wrap",f);g[1](3,"wrapc",function(a,c,b){return f(!1,!1,a,c,b)});g[1](3,"wrape",function(a,c){return f(!1,!1,!1,a,c)});g[1](3,"wrapne",function(a,c,b){return f(a,!1,!1,c,b)});g[1](3,
"wrapna",function(a,c){return f(a,!1,!1,!1,c)});g[1](3,"textNode",a);g[1](3,"bubbleUp",c);g[1](3,"chainUpApply",d);g[1](3,"id",function(a,c){var d=document.getElementById(a);return d?c&&b()?s(d):d:d});g[1](3,"tag",function(a,c,b){b=void 0===b?document:b;return e(b.getElementsByTagName(a),c)});g[1](3,"name",function(a,c,b){b=void 0===b?document:b;return e(b.getElementsByName(a),c)});g[1](3,"glass",function(a,c,b){b=void 0===b?document:b;return e(b.getElementsByClassName(a),c)})})();BotanJS.define("System.utils.EventKey");
(function(){function b(c,a){d.call(this,c,a);this.type=c.toLowerCase();this.handler=a}var e=B("System.utils"),d=e[0]("IKey");k(b,d);b.prototype.type="";b.prototype.handler=null;e[1](2,"EventKey",b)})();BotanJS.define("Dandelion.IDOMObject");
(function(){function b(a,c){if(a instanceof b)return a;if(c)this.addEventListener=this.addEventListener.bind(a),this.addEventListeners=this.addEventListeners.bind(this),this.hasListener=this.hasListener.bind(a),this.removeEventListener=this.removeEventListener.bind(a);else{if(a)return new b(a,!0);throw Error("[Dandelion.IDOMObject] Invalid argument");}}function e(){}var d=B("Dandelion"),c=C("System.utils.EventKey");e.prototype.indexOf=function(a){for(var c=this.length,b=0;b<c;b++){var d=this[b];if(d.type==
a.type&&d.handler==a.handler)return b}return-1};k(e,Array);b.prototype.hasListener=function(a){return a instanceof c&&this.b&&-1!=this.b.indexOf(a)?this.b[this.b.indexOf(a)]:null};b.prototype.addEventListener=function(a,b){var d;if("string"==typeof a&&b)d=new c(a,b);else if(a instanceof c)d=a;else return!1;if(this.b)if(0>this.b.indexOf(d))this.b.push(d);else return!1;else this.b=new e,this.b[0]=d;this.addEventListener?this.addEventListener(d.type,d.handler,!1):this.attachEvent?this.attachEvent("on"+
d.type,d.handler):this["on"+d.type]=d.handler;return!0};b.prototype.addEventListeners=function(a){if(a instanceof Array)for(var c in a)this.addEventListener(a[c])};b.prototype.removeEventListener=function(a,b){b&&(a=new c(a,b));this.b&&delete this.b[this.b.indexOf(a)];this.removeEventListener?this.removeEventListener(a.type,a.handler):this.detachEvent?this.detachEvent("on"+a.type,a.handler):this["on"+a.type]=null};d[1](2,"IDOMObject",b)})();BotanJS.define("Dandelion.IDOMElement");
(function(){function b(a){a=typeof a;return"number"==a?d:"string"==a?e:c}function e(a,c){return a.nodeName==c}function d(a,c){return a.nodeType==c}function c(){return!1}function a(c,b){if(c instanceof a)return c;if(b)n.call(this,c,!0),this.getDAttribute=this.getDAttribute.bind(c),this.lootChildren=this.lootChildren.bind(c),this.foreach=this.foreach.bind(c),this.reverseChild=this.reverseChild.bind(c),this.first=this.first.bind(c),this.last=this.last.bind(c),this.contains=this.contains.bind(c),this.style=
c.style,this.hasAttribute=function(){}.bind(c),this.removeAttribute=function(a){this.removeAttribute(a)}.bind(c),this.element=c,this.setAttribute=this.setAttribute.bind(c);else{if(c&&void 0!=c.nodeType&&1==c.nodeType)return new a(c,!0);if(void 0===c)return new a(g(),!0);throw Error("[Dandelion.IDOMElement] Invalid argument");}return this}var f=B("Dandelion"),h=C("System.utils.IKey");C("System.utils.Perf");var g=f[0]("wrap"),n=f[0]("IDOMObject");k(a,n);a.prototype.setAttribute=function(a,c){if(a instanceof
h)this.setAttribute(a.keyName,a.keyValue);else if(a instanceof Array)for(var b in a)a[b]instanceof h&&this.setAttribute(a[b].keyName,a[b].keyValue);else this.setAttribute(a,c)};a.prototype.lootChildren=function(a){for(var c=a.childNodes;c.length;)this.appendChild(a.removeChild(c[0]))};a.prototype.getDAttribute=function(a){return(a=this.getAttribute("data-"+a))&&decodeURIComponent(a)};a.prototype.foreach=function(a,c){for(var b=Array.apply([],this.childNodes),d=b.length,f=0;f<d;f++)b[f].nodeType==
a&&c(b[f],this)};a.prototype.first=function(a,c){for(var d=this.childNodes,f=d.length,e=null,h=b(a),g=0;g<f;g++)if(h(d[g],a)&&(void 0===c||c(d[g],this))){e=d[g];break}return e};a.prototype.last=function(a,c){for(var d=this.childNodes,f=null,e=b(a),g=d.length-1;-1<g;g--)if(e(d[g],a)&&(void 0===c||c(d[g],this))){f=d[g];break}return f};a.prototype.contains=function(a){return a.parentElement?a==this?!0:this.contains(a.parentElement):!1};a.prototype.aKeys=function(){for(var a=[],c=this.element.attributes,
b=c.length,d=0;d<b;d++)a.push(new h(c[d].name,c[d].value));return a};a.prototype.reverseChild=function(){for(var a=this.childNodes.length-1;-1<--a;)this.appendChild(this.childNodes[a])};f[1](2,"IDOMElement",a)})();BotanJS.define("System.utils.DataKey");(function(){function b(c,a){d.call(this,"data-"+c,a?encodeURIComponent(String(a)):"")}var e=B("System.utils"),d=e[0]("IKey");k(b,d);e[1](2,"DataKey",b)})();BotanJS.define("System.utils");
(function(){var b=B("System.utils"),e=C("System.Global");b[1](3,"objGetProp",function(b,c,a){if(b&&b[c]){var f=b[c].constructor.toString().match(/function ([^\(]+)/);if(f&&2==f.length&&f[1].toUpperCase()==a.toUpperCase())return b[c]}return null});b[1](3,"objSearch",function(b,c,a){for(var f in b)if(c(b[f]))return b[f][a]||b[f];return null});b[1](3,"objMap",function(b,c){for(var a in b)b[a]=c(b[a])});b[1](3,"siteProto",function(b){return b.match(/^https?:\/\//)?e.SECURE_HTTP?b.replace(/^http:\/\//,
"https://"):b.replace(/^https:\/\//,"http://"):"http"+(e.SECURE_HTTP?"s":"")+"://"+b})})();BotanJS.define("System.Tick");
(function(){function b(){var b=0;this.e=!1;this.loop=function(){for(var c in this.steppers)this.steppers[c]();b++};l(this,"count",function(){return b})}var e=B("System");b.prototype.putStepper=function(b){var c=this.steppers.length;this.steppers[c]=b;return c};b.prototype.start=function(){this.e||(this.id=setInterval(this.loop.bind(this),0),this.e=!0)};b.prototype.stop=function(){this.e&&(this.e=!1,clearInterval(this.id))};b.prototype.steppers=[];l(b.prototype,"started",function(){return this.e});
e[1](2,"Tick",b)})();BotanJS.define("System.Log");(function(){var b=B("System.Log"),e=[];b[1](3,"writeLine",function(b,c){c=void 0===c?16:c;var a=!1,f;for(f in e)e[f](b,c),a=!0;!a&&window.console&&console.log&&console.log(b)});b[1](3,"registerHandler",function(b){var c=-1;e[c=e.length]=b;return c});b[1](3,"removeHandler",function(b){delete e[b]});b[1](0,"INFO",16);b[1](0,"ERROR",32);b[1](0,"SYSTEM",1)})();BotanJS.define("System.Debug");
(function(){function b(a){c&&d.writeLine(a,d.INFO)}var e=B("System.Debug"),d=C("System.Log"),c=C("System.Global").debug,a=!0;for(BotanJS.log.write=b;!BotanJS.log.end();)b(BotanJS.log.read());e[1](3,"Error",function(c){a&&d.writeLine(c.name+"\n\t"+c.message+"\n\t"+c.stack,d.ERROR)});e[1](3,"Info",b);e[1](3,"turnOff",function(b){"info"==b?c=!1:"error"==b&&(a=!1)});e[1](3,"turnOn",function(b){"info"==b?c=!0:"error"==b&&(a=!0)})})();BotanJS.define("System.Cycle");
(function(){function b(a){a.target.removeEventListener("NS_IMPORT",b);a=C("System.Cycle.TICK",!0);a!=f&&a.w?(c.Info("[System.Cycle] Global Tick exists"),f=null):(c.Info("[System.Cycle] Creating global Tick"),f.start())}var e=B("System.Cycle");C("System.utils");var d=C("System.Tick"),c=C("System.Debug"),a=[],f=new d;f.putStepper(function(){var b=(new Date).getTime(),d;for(d in a){var f=a[d];if(f&&b>f[1]){try{f[0]()}catch(e){c.Error(e);delete a[d];continue}f[2]?delete a[d]:f[1]=b+f[4]}}});e.addEventListener("NS_IMPORT",
b);e[1](3,"next",function(c){a[a.length]=[c,0,!0]});e[1](3,"delay",function(c,b){a[a.length]=[c,(new Date).getTime()+b,!0]});e[1](3,"perma",function(c,b,d){for(var f in a)if(a[f][3]==c)return!1;a[a.length]=[b,(new Date).getTime()+d,!1,c,d]});e[1](3,"permaRemove",function(c){for(var b in a)a[b][3]==c&&delete a[b]});e[1](10,"TICK",function(){return f})})();BotanJS.define("Components.Vim.LineBuffer");
(function(){function b(b,c){this.prev=null;this.cols=b;this.next=c;this.br=!1;this.placeholder=!0;this.lineNum=0;this.tabWidth=8;c&&(c.prev=this)}var e=B("Components.Vim");C("System.Debug");b.prototype.g=function(b,c,a){this.lineNum=a;if(void 0==b||""===b)this.lineNum=++a,this.content="~",this.placeholder=this.br=!0,this.next&&this.next.g(b,c,a+1);else{this.placeholder=!1;var f="",e=!1,g=0,n=0;if(c)for(;g<this.cols-n*this.tabWidth;g++){var m=b[g];if(void 0===m)break;if("\n"==m){e=!0;g++;break}else"\t"==
m&&n++;f+=m}else for(e=!0;;g++){m=b[g];if(void 0===m)break;if("\n"==m){g++;break}else"\t"==m&&n++;g<this.cols-n*this.tabWidth&&(f+=m)}this.next&&(this.next.br=e,this.next.g(b.substr(g),c,e?a+1:a));this.content=f}};b.prototype.toString=function(){return this.content||" "};l(b.prototype,"nextLine",function(){for(var b=this,c=this.lineNum;(b=b.next)&&b.lineNum==c;);return b});l(b.prototype,"visualLines",function(){for(var b=[this],c=this;(c=c.next)&&!c.br;)b.push(c);return b});e[1](2,"LineBuffer",b)})();
BotanJS.define("Components.Vim");
(function(){function b(a,b,c){if(void 0==a[b])return b;var d=0;return a[b].replace(/%\d+/g,function(){return c[d++]})}var e=B("Components.Vim"),d={INSERT:"-- INSERT --",REPLACE:"-- REPLACE --",MORE:"-- MORE --",VISLINE:"-- VISUAL LINE --",WRITE:'"%1" %2L, %3C written',CONTINUE:"Press ENTER or type command to continue",SEARCH_HIT_BOTTOM:"Seach hit BOTTOM, contining at TOP",TOP:"Top",BOTTOM:"Bot",ALL:"All",EXIT:"Type :quit<Enter>  to exit Vim"},c={E486:"E486: Pattern not found: %1"};e[1](3,"Message",
function(a){return b(d,a,Array.prototype.slice.call(arguments,1))});e[1](3,"Error",function(a){return b(c,a,Array.prototype.slice.call(arguments,1))})})();BotanJS.define("Components.Vim.Actions.INSERT");
(function(){function b(b){this.cursor=b}var e=B("Components.Vim.Actions");C("System.Debug");var d=C("Components.Vim.Message");b.prototype.dispose=function(){};b.prototype.handler=function(b){b.preventDefault()};b.prototype.getMessage=function(){for(var b=this.cursor.feeder.firstBuffer.cols,a=d("INSERT"),f=a.length;f<b;f++)a+=" ";return a};e[1](2,"INSERT",b)})();BotanJS.define("Components.Vim.Cursor");
(function(){function b(b){this.feeder=b;this.cols=b.firstBuffer.cols;this.P=this.Y=this.X=this.pX=0;this.action=null}var e=B("Components.Vim");C("System.Debug");var d=C("Components.Vim.Actions.*");b.prototype.moveX=function(b){var a=this.pX,d=Boolean(b);d&&(a=this.X+b);b||(b=1);var e=this.Y,g=this.feeder.lineBuffers[0];e++;for(var n=0,m=g;m&&n<e;n++)for(g=m;m&&(m=m.next,!m.br););e=g.visualLines.join("\n");g=e[a];void 0==g?a=0<b?e.length-1:0:"\n"==g&&(a+=b);this.X=a;d&&(this.pX=a,this.updatePosition())};
b.prototype.lineStart=function(){this.pX=0;this.moveX();this.updatePosition()};b.prototype.lineEnd=function(){this.moveX(Number.MAX_VALUE)};b.prototype.updatePosition=function(){var b=0,a=0,d=this.feeder.lineBuffers[0];a:for(;d&&a<this.Y;a++)for(;d;){if(d.next&&d.next.placeholder)break a;b+=d.toString().length+1;if((d=d.next)&&d.br)break}this.P=this.X+b;this.feeder.dispatcher.dispatchEvent(new BotanEvent("VisualUpdate"))};b.prototype.moveY=function(b){var a=this.Y+b,d;if(0>a)this.feeder.pan(void 0,
b),this.Y=0,this.moveX(),this.updatePosition(),this.feeder.softReset();else if(this.feeder.moreAt<a){b=this.feeder;d=b.lastBuffer.lineNum;for(var a=a-b.moreAt,e=0;;)if(b.pan(void 0,a+e),b.lastBuffer.lineNum==d)e++;else break;a=d+a;e=0;for(d=b.firstBuffer;d!=b.lastBuffer&&(d.br&&e++,d.lineNum!=a);d=d.next);this.Y=e;this.moveX();this.updatePosition();b.softReset()}else{if(0<b&&(d=this.p().nextLine,!d||d.placeholder))return;this.Y=a;this.moveX();this.updatePosition()}};b.prototype.openAction=function(b){this.action&&
this.action.dispose();this.action=new d[b](this);this.feeder.dispatcher.dispatchEvent(new BotanEvent("VisualUpdate"))};b.prototype.closeAction=function(){this.action&&(this.action.dispose(),this.action=null,this.feeder.dispatcher.dispatchEvent(new BotanEvent("VisualUpdate")))};b.prototype.p=function(){for(var b=this.feeder,a=b.firstBuffer,d=0;a!=b.lastBuffer&&(a.br&&d++,this.Y!=d);a=a.next);return a};l(b.prototype,"message",function(){return this.action&&this.action.getMessage()});l(b.prototype,"position",
function(){return{start:this.P,end:this.P+1}});e[1](2,"Cursor",b)})();BotanJS.define("Components.Vim.LineFeeder");
(function(){function b(a,b){var e=[];e[a]=new d(b);for(var g=a-1;0<=g;g--)e[g]=new d(b,e[g+1]);this.lineBuffers=e;this.panY=this.panX=0;this.setRender();this.cursor=new c(this);this.dispatcher=new t;this.d=null;this.h=-1;this.i=a;this.m=!0}var e=B("Components.Vim");C("System.Debug");var d=e[0]("LineBuffer"),c=e[0]("Cursor");b.prototype.init=function(a,b){this.content=a;this.setWrap(b);this.firstBuffer.g(a,this.m,0)};b.prototype.setWrap=function(a){void 0!=a&&(this.m=a)};b.prototype.setRender=function(a){void 0==
a&&(a=!0);var b=this,c=a?function(){return!0}:function(a){return!a.placeholder};this.u=function(a,d){for(var e=(void 0==a?"":a)+"",s=!1,z=0;a&&z<d&&(a=a.next)&&c(a);z++)s||a.br&&d<z+a.visualLines.length?(s||(b.d=a),s=!0,e+="\n@"):e+="\n"+a;return e};this.v=function(){for(var a=b.lineBuffers[b.t],d=b.o,e=0;a&&e<d&&(a=a.next)&&c(a);e++)if(a.br&&d<e+a.visualLines.length){b.d=a;break}}};b.prototype.render=function(a,b){var c=this.lineBuffers;if(void 0==a)a=0;else if(this.i<a)return"";if(void 0==b||this.i-
a<b)b=this.rows-a;if(0==b)return"";this.t=a;this.o=b-1;return this.u(c[a],this.o)};b.prototype.pan=function(a,b){void 0==a&&(a=0);void 0==b&&(b=0);if(0!=a||0!=b){var c=this.panX+a,d=this.panY+b,e=-1,m=0;0>d&&(d=0);if(0<d)for(e=this.content.indexOf("\n"),m=1;-1!=e&&m<d;m++)e=this.content.indexOf("\n",e+1);this.firstBuffer.g(this.content.substr(e+1),this.m,m);this.panX=c;this.panY=d}};b.prototype.softReset=function(){this.h=-1;this.d=null;this.v()};l(b.prototype,"firstBuffer",function(){return this.lineBuffers[0]});
l(b.prototype,"lastBuffer",function(){return this.lineBuffers[this.i-1]});l(b.prototype,"EOF",function(){return this.lineBuffers[this.i].placeholder});l(b.prototype,"moreAt",function(){if(0<this.h)return this.h;var a=this.firstBuffer;if(a.placeholder)return 0;var b=0;do{if(this.d==a)break;a.br&&b++}while(a=a.next);void 0==a&&b--;return this.h=b});l(b.prototype,"lineStat",function(){var a=this.cursor.X,b=this.cursor.p(),c="",d=b.content.match(/\t/g);d&&(c="-"+(a+d.length*b.tabWidth));return b.lineNum+
1+","+a+c});l(b.prototype,"docPos",function(){var a="ALL";if(0<this.panY&&this.EOF)a="BOTTOM";else if(this.d||!this.EOF)a="TOP";return a});l(b.prototype,"linesOccupied",function(){var a=this.firstBuffer;if(a.placeholder)return 0;var b=0;do b++;while((a=a.next)&&!a.placeholder);return b});e[1](2,"LineFeeder",b)})();BotanJS.define("Components.Vim.StatusBar");
(function(){function b(b){this.cols=b;this.n={}}var e=B("Components.Vim");C("System.Debug");e[0]("LineFeeder");b.prototype.stamp=function(b,c){this.n[b]=c};l(b.prototype,"statusText",function(){for(var b="",c=this.cols,a=0;a<c;a++){var e=c-a,h=this.n[a]||this.n[-e];h?(h=h(),void 0!=h&&""!==h&&(b+=h.substr(0,e),a=b.length-1)):b+=" "}return b});e[1](2,"StatusBar",b)})();BotanJS.define("Components.Vim.Controls");
(function(){var b=B("Components.Vim");C("System.Debug");b[1](3,"Controls",function(b,d){if(!(d.altKey||112<d.keyCode&&124>d.keyCode)){var c=b.contentFeeder;if(c.cursor.action)27==d.keyCode||d.ctrlKey&&67==d.keyCode?(d.preventDefault(),c.cursor.closeAction()):c.cursor.action.handler(d);else if(d.preventDefault(),d.ctrlKey)VimComboFunc(b,d);else{var a=d.keyCode+(d.shiftKey?1E3:0),c=b.contentFeeder;switch(a){case 72:c.cursor.moveX(-1);break;case 74:c.cursor.moveY(1);break;case 75:c.cursor.moveY(-1);
break;case 76:c.cursor.moveX(1);break;case 65:c.cursor.openAction("INSERT");break;case 1052:c.cursor.lineEnd();break;case 1054:c.cursor.lineStart()}}}})})();BotanJS.define("Components.Vim.VimArea");
(function(){function b(a){if(a){var b=a.element;if("TEXTAREA"!=b.nodeName)f.Error("Element is not compatible for VimArea");else{a.setAttribute(new c("vimarea",1));this.stage=a;this.rows=b.rows;this.cols=b.cols;this.k=!1;var d=this;a.addEventListener("KeyDown",e(this,n));a.addEventListener("Focus",function(){d.k=!0});a.addEventListener("Blur",function(){d.k=!1});this.q(b.value)}}}function e(a,b){return function(c){c=c||window.event;c.keyCode?code=c.keyCode:c.which&&(code=c.which);b(a,c)}}var d=B("Components.Vim");
C("Dandelion.IDOMElement");var c=C("System.utils.DataKey"),a=C("System.Cycle"),f=C("System.Debug"),h=d[0]("LineFeeder"),g=d[0]("StatusBar"),n=d[0]("Controls"),m=d[0]("Message");b.prototype.select=function(a){if(this.k){var b=this.stage.element;a&&(b.selectionStart=a.start,b.selectionEnd=a.end)}};b.prototype.q=function(b){function c(){sfeeder.init(u.statusText);e.value=r.render(0,f-sfeeder.linesOccupied)+"\n"+sfeeder.render();d.l=!1;d.select(r.cursor.position)}var d=this,e=this.stage.element,f=this.rows,
n=this.cols,r=new h(f-1,n);r.init(b);sfeeder=new h(f,n);sfeeder.setRender(!1);var u=new g(n);u.stamp(-18,function(){return r.lineStat});u.stamp(-3,function(){return m(r.docPos)});u.stamp(0,function(){return r.cursor.message});sfeeder.init(u.statusText);r.dispatcher.addEventListener("VisualUpdate",c);c();this.contentFeeder=r;this.statusFeeder=sfeeder;this.statusBar=u;this.s=r.cursor;this.l=!0;a.perma("VimCursorBlinkCycle"+e.id,function(){d.select((d.l=!d.l)?d.s.position:{start:0,end:0})},600)};l(b.prototype,
"content",function(){return this.contentFeeder.content});d[1](2,"VimArea",b)})();})();
