(function(){function h(a,d){Object.defineProperty(a,"propagating",{get:d,set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:"propagating"})})}function k(a,d,c){Object.defineProperty(a,d,{get:function(){return c},set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:d})})}
function BotanEvent(a,d){var c=!1,b=!1;k(this,"propagate",function(){b||(c=!0);b=!0});k(this,"stopPropagating",function(){c=!1});k(this,"type",a);h(this,function(){return c});k(this,"data",d);this.setTarget=function(a){k(this,"target",a);this.setTarget=void 0}.bind(this)}
function l(){function a(){this.d.propagate();for(var a in this.stack)if(this.d.propagating)this.stack[a](this.d);this.d.stopPropagating()}function d(a){c[a]||(c[a]=[]);return c[a]}var c={},b=this;this.addEventListener=function(a,f){var b=d(a);b[b.length]=f};this.removeEventListener=function(a,f){var b=d(a),c=b.indexOf(f);0>c||delete b[c]};this.dispatchEvent=function(c){var f=d(c.type);c.setTarget&&c.setTarget(b);setTimeout(a.bind({d:c,stack:f}),0)}}function m(){l.call(this)}m.prototype=[];
var n={},p={},q={},r=window.BotanJS,BotanJS=null,s=null,t=null;r&&(BotanJS=r.sg[0],s=r.sg[1],t=r.sg[2]);BotanJS=BotanJS||function(){var a=0,d=[],c=[],b=new l,e={write:function(a){d[d.length]=a}};k(e,"read",function(){return d[a++]});k(e,"end",function(){return d.length<=a});k(b,"log",e);k(b,"define",function(a){c[c.length]=a});k(b,"getDef",function(){return c.slice()});return b}();
s=s||function(a){if(p[a])return p[a];for(var d=a.split("."),c=d.length,b=n,e=0;e<c;e++)b[d[e]]=b[d[e]]||{},b=b[d[e]];b.e=[];nsObj=new m;nsObj[1]=function(a,b,c){this.b[b]||(this.b[b]=[a,c],a=new BotanEvent("NS_EXPORT",{name:this.c+"."+b,type:a}),BotanJS.dispatchEvent(a))}.bind({b:b,c:a});nsObj[0]=function(a){if(!this.b[a])throw Error("["+this.c+"] Invoke failed: "+a+" does not exists");return this.b[a][1]}.bind({b:b,c:a});nsObj[10]=function(a,b){this.e[a]=b}.bind(b);nsObj[11]=function(a,b){throw Error("["+
this.c+(b?"."+b:"")+"] "+a);}.bind({c:a});BotanJS.dispatchEvent(new BotanEvent("NS_INIT",a));return p[a]=nsObj};
t=t||function(a,d){var c=a.replace(".*","");p[c]&&p[c].dispatchEvent(new BotanEvent("NS_IMPORT",f));if(!d&&q[a])return q[a];for(var b=a.split("."),e=b.length,f=n,c=!1,g=0;g<e;g++){if("*"==b[g]){c=!0;break}f=f[b[g]];if(!f)throw Error("No such class: "+a);}if(f instanceof Array&&"*"!=b[g])return c=null,c=10==f[0]?f[1]():f[1],q[a]=c;b={};for(g in f)e=f[g],e instanceof Array&&(c&&2==e[0]?b[g]=e[1]:3==e[0]?b[g]=e[1]:0==e[0]?Object.defineProperty(b,g,{get:function(){return this.b[this.a][1]}.bind({a:g,
b:f}),set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:g})}):1==e[0]?Object.defineProperty(b,g,{get:function(){return this.b[this.a][1]()}.bind({a:g,b:f}),set:function(a){this.b[this.a][1](a)}.bind({a:g,b:f})}):10==e[0]&&Object.defineProperty(b,g,{get:e[1],set:function(){throw Error("Setting a read-only property: "+this.a);}.bind({a:g})}));return q[a]=b};window.BotanJS={};window.BotanJS.version="1.0.0b";window.BotanJS.codename="Botanical framework.js";
window.BotanJS["import"]=function(a){try{return t(a)}catch(d){if(r)return r["import"](a);throw d;}};window.BotanJS.sg=[BotanJS,s,t];BotanJS.define("System.Log");
(function(){var a=s("System.Log"),d=[];a[1](3,"writeLine",function(a,b){b=void 0===b?16:b;var e=!1,f;for(f in d)d[f](a,b),e=!0;!e&&window.console&&console.log&&console.log(a)});a[1](3,"registerHandler",function(a){var b=-1;d[b=d.length]=a;return b});a[1](3,"removeHandler",function(a){delete d[a]});a[1](0,"INFO",16);a[1](0,"ERROR",32);a[1](0,"SYSTEM",1)})();BotanJS.define("System.Global");
(function(){var a=s("System.Global"),d=Boolean(document.all),c=window.allowed_origins||[],b=window.location.href.match(/^https:\/\//);a[1](10,"debug",function(){return window.debugEnv&&window.debugEnv});a[1](0,"IE",d);a[1](0,"ALLOWED_ORIGINS",c);a[1](0,"SECURE_HTTP",b)})();BotanJS.define("System.Debug");
(function(){function a(){b&&c.writeLine(Array.prototype.join.call(arguments," "),c.INFO)}var d=s("System.Debug"),c=t("System.Log"),b=t("System.Global").debug,e=!0;for(BotanJS.log.write=a;!BotanJS.log.end();)a(BotanJS.log.read());d[1](3,"Error",function(a){e&&c.writeLine(a.name+"\n\t"+a.message+"\n\t"+a.stack,c.ERROR)});d[1](3,"Info",a);d[1](3,"turnOff",function(a){"info"==a?b=!1:"error"==a&&(e=!1)});d[1](3,"turnOn",function(a){"info"==a?b=!0:"error"==a&&(e=!0)})})();BotanJS.define("Dandelion.CSSReset");
BotanJS.define("Dandelion.CSSAnimations");BotanJS.define("Astro.Bootstrap");
(function(){var a=s("Astro.Bootstrap"),d=t("System.Debug"),c=[],b=!1,e=!1,f=!1;BotanJS.addEventListener("NS_EXPORT",function(a){switch(a.data.name){case "Components.Console":e=!0;break;case "Libraries.SyntaxHighlighter":f=!0}});try{t("Components.Console"),e=!0}catch(g){}a[1](3,"init",function(){if(!b){b=!0;e&&new (t("Components.Console"));var a=c.length;d.Info("[Astro.Blog] init("+a+")");for(var g=0;g<a;g++)c[g]();f&&(d.Info("[SyntaxHighlighter] Initializing"),a=t("Libraries.SyntaxHighlighter"),a.defaults.toolbar=
!1,a.defaults["quick-code"]=!1,a.highlight())}});a[1](3,"regInit",function(a){c[c.length]=a})})();BotanJS.define("Astro.Penguin.Github");s("Astro.Penguin.Github");t("Astro.Bootstrap");})();
